project/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.Register.as_view(), name='register'),
]

project/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/authapp/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class ExamUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, login, email, password, **extra_fields):
        """
        Create and save a user with the given login, email, and password.
        """
        if not login:
            raise ValueError('The given login must be set')
        email = self.normalize_email(email)
        user = self.model(login=login, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, login, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(login, email, password, **extra_fields)

    def create_superuser(self, login, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(login, email, password, **extra_fields)


class ExamUser(AbstractUser):
    objects = ExamUserManager()

    username = None
    first_name = None
    last_name = None

    login = models.CharField(
        'login',
        max_length=150,
        unique=True,
        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[AbstractUser.username_validator],
        error_messages={
            'unique': "A user with that login already exists.",
        },
    )
    USERNAME_FIELD = 'login'

    name = models.CharField('name', max_length=30)
    surname = models.CharField('surname', max_length=50)
    patronymic = models.CharField('patronymic', max_length=50, blank=True)
    email = models.EmailField('email address')
    rules = models.BooleanField('rules', default=True)

    def get_full_name(self):
        full_name = '%s %s' % (self.name, self.surname)
        return full_name.strip()

project/mainapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField('Название', max_length=60)
    desc = models.TextField('Описание', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField('Название', max_length=60)
    desc = models.TextField('Описание', blank=True)
    photo = models.ImageField('Фото', upload_to='images/products/', blank=True)
    # product_model = models.CharField('Модель', max_length=30)
    country = models.CharField('Страна-Производитель', max_length=30)
    year = models.IntegerField('Год выпуска')
    price = models.DecimalField('Цена', max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

project/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from authapp.models import ExamUser


class LoginForm(AuthenticationForm):
    class Meta:
        model = ExamUser
        fields = ('login', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = ExamUser
        fields = ('name', 'surname', 'patronymic', 'login', 'password1', 'password2', 'rules')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

project/authapp/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from authapp.forms import RegisterForm, LoginForm


class Register(CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('auth:login')
    template_name = 'authapp/register.html'


class Login(LoginView):
    form_class = LoginForm
    template_name = 'authapp/login.html'


class Logout(LogoutView):
    success_url = reverse_lazy('auth:login')

project/mainapp/views.py
from django.shortcuts import render


def index(request):
    context = {
        'page_title': 'главная'
    }
    return render(request, 'mainapp/index.html', context)

project/authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:'Аутентификация'|capfirst }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

project/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
<div class="login-form"
     style="width: 200px; margin: 5vh auto; padding-top: 250px; margin-bottom: 25px;">
    <div class="form-title"
         style="text-align: center; font-weight: bold; font-size: larger;">Вход в систему
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"
               class="btn btn-success form-control text-center"
               value="Войти"
               style=" width: 200px;">
    </form>
    <br>
    <a class="btn btn-danger form-control text-center"
       style=" width: 200px;"
       href="{% url 'auth:register' %}">
        Зарегистрироваться
    </a>
</div>
{% endblock %}

project/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content %}
<div class="register-form"
     style="width: 200px; margin: 5vh auto; padding-top: 250px; margin-bottom: 25px;">
    <div class="form-title"
         style="text-align: center; font-weight: bold; font-size: larger;">
        Регистрация
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"
               class="btn btn-danger form-control text-center"
               value="Зарегистрироваться"
               style=" width: 200px;">
    </form>
</div>
{% endblock %}

project/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"Главная"|capfirst }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block menu %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'mainapp:index' %}">Главная</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">О нас</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Каталог</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Где нас найти?</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Корзина</a>
        </li>
        <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>

            {% else %}
            <a class="nav-link" href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
</nav>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

project/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<h1>Главная страница работает!</h1>
{% endblock %}